name: Test & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: setup psql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql password: password
          postgresql user: girassol
      - name: install dependencies
        run: npm ci
      - name: run utils tests
        run: npm run test-utils
      - name: run tests
        run: PGDATABASE=test_db PGPASSWORD=password PGUSER=girassol npm run test-app
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to Render
        run: NODE_ENV=production curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}