name: Test & Deploy
on:
  pull_request:
    branches:
      - main

jobs:
  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo and checkout main
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm run test-utils
  test-app:
    runs-on: ubuntu-latest
    needs: test-utils
    steps:
      - name: clone repo and checkout main
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: setup psql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql password: password
          postgresql user: girassol
      - name: run tests
        run: PGDATABASE=test_db PGPASSWORD=password PGUSER=girassol npm run test-app
  test-live-db:
    runs-on: ubuntu-latest
    needs: test-app
    steps:
      - name: clone repo and checkout main
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: run tests
        run: NODE_ENV=production DATABASE_URL = ${{ secrets.DATABASE_URL }} npm run test-app
